close all

% Load Error results
load yaapt_error_eval.mat
load baffe_error_eval.mat

M = zeros(25,length(BAFFE_RESULTS.SNRZ));

M(1 ,:) = BAFFE_RESULTS.SNRZ;
M(2 ,:) = YAAPT_RESULTS.STUDIO_WHITE.GROSS5;
M(3 ,:) = BAFFE_RESULTS.STUDIO_WHITE.GROSS5;
M(4 ,:) = YAAPT_RESULTS.STUDIO_WHITE.GROSS20;
M(5 ,:) = BAFFE_RESULTS.STUDIO_WHITE.GROSS20;
M(6 ,:) = YAAPT_RESULTS.STUDIO_WHITE.FINE;
M(7 ,:) = BAFFE_RESULTS.STUDIO_WHITE.FINE;
M(8 ,:) = YAAPT_RESULTS.STUDIO_BABBLE.GROSS5;
M(9 ,:) = BAFFE_RESULTS.STUDIO_BABBLE.GROSS5;
M(10,:) = YAAPT_RESULTS.STUDIO_BABBLE.GROSS20;
M(11,:) = BAFFE_RESULTS.STUDIO_BABBLE.GROSS20;
M(12,:) = YAAPT_RESULTS.STUDIO_BABBLE.FINE;
M(13,:) = BAFFE_RESULTS.STUDIO_BABBLE.FINE;
M(14,:) = YAAPT_RESULTS.TELE_WHITE.GROSS5;
M(15,:) = BAFFE_RESULTS.TELE_WHITE.GROSS5;
M(16,:) = YAAPT_RESULTS.TELE_WHITE.GROSS20;
M(17,:) = BAFFE_RESULTS.TELE_WHITE.GROSS20;
M(18,:) = YAAPT_RESULTS.TELE_WHITE.FINE;
M(19,:) = BAFFE_RESULTS.TELE_WHITE.FINE;
M(20,:) = YAAPT_RESULTS.TELE_BABBLE.GROSS5;
M(21,:) = BAFFE_RESULTS.TELE_BABBLE.GROSS5;
M(22,:) = YAAPT_RESULTS.TELE_BABBLE.GROSS20;
M(23,:) = BAFFE_RESULTS.TELE_BABBLE.GROSS20;
M(24,:) = YAAPT_RESULTS.TELE_BABBLE.FINE;
M(25,:) = BAFFE_RESULTS.TELE_BABBLE.FINE;

csvwrite('results_text.csv',M)

